export const examsData = [
  {
    id: 1,
    title: "3-cü sinif imtahanı",
    duration: 45,
    reviews: 2,
    questions: 10,
    subjects: ["Azərbaycan dili", "Riyaziyyat"],
  },
  {
    id: 2,
    title: "3-cü sinif imtahanı",
    duration: 45,
    reviews: 2,
    questions: 10,
    subjects: ["Azərbaycan dili", "Riyaziyyat"],
  },
  {
    id: 3,
    title: "3-cü sinif imtahanı",
    duration: 45,
    reviews: 2,
    questions: 10,
    subjects: ["Azərbaycan dili", "Riyaziyyat"],
  },
  {
    id: 4,
    title: "3-cü sinif imtahanı",
    duration: 45,
    reviews: 2,
    questions: 10,
    subjects: ["Azərbaycan dili", "Riyaziyyat"],
  },
  {
    id: 5,
    title: "3-cü sinif imtahanı",
    duration: 45,
    reviews: 2,
    questions: 10,
    subjects: ["Azərbaycan dili", "Riyaziyyat"],
  },
  {
    id: 6,
    title: "3-cü sinif imtahanı",
    duration: 45,
    reviews: 2,
    questions: 10,
    subjects: ["Azərbaycan dili", "Riyaziyyat"],
  },
];
